version: '3.7'
services:
  management:
    build: ./management/
    image: festival_management:latest
    volumes:
      - ./management/:/management
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  data:
    build: ./data_api/
    volumes:
      - ./data_api/:/data
    depends_on:
      - db

  terminal:
    build: ./terminal/
    image: terminal:latest
    volumes:
      - ./terminal/:/terminal
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  sidekiq:
    build: ./management/
    command: sidekiq
    volumes:
      - ./management/:/management
    environment:
      REDIS_URL: redis://redis:6379/0
      
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:

