version: '3.7'
services:
  management:
    build: ./management
    command: rails s -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - ./management:/management
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  data:
    build: ./data_api/
    command: rails s -b 0.0.0.0
    volumes:
      - ./data_api/:/data
    ports:
      - 8080:3000
    depends_on:
      - db

  terminal:
    build: ./terminal/
    volumes:
      - ./terminal/:/terminal
    depends_on:
      - db


  db:
    image: postgres:11.5
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

  sidekiq:
    build: ./management
    command: sidekiq
    volumes:
      - ./management:/management
    environment:
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:

