version: '3'
services:
  data:
    build: ./data_api/
    volumes:
      - ./data_api/:/data
    ports:
      - 3000:3000
    depends_on:
      - db

  terminal:
    build: ./terminal/
    image: terminal:latest
    container_name: terminal
    volumes:
      - ./terminal/:/terminal
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:11.5
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
