version: '3'
services:
  data:
    build: ./data/
    volumes:
      - ./data/:/data
    ports:
      -3000:3000
    depends_on:
      - db
  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
